### ISSUE TITLE
Warning: React.createElement: type is invalid

### ISSUE THREAD

**Issue by flyfishMT** [Hermanya/react-bootstrap-navbar-offcanvas#33]
Hi, I get a blank page trying to get this to run (same with your demo page). I get an error "Warning: React.createElement: type is invalid" in the console.  Thanks

**Comment by Hermanya** [comment]
Thanks for reporting this, I will take a look

**Comment by Hermanya** [comment]
In the example, I forgot to lock the react-bootstrap version to 0.32.0.
But fixing that did not help with a missing css file, which I know don't remember anything about 😞

**Comment by flyfishMT** [comment]
Ok I'm using the latest react-bootstrap locally too that must be the problem.  Will you be supporting the latest react-bootstrap when it comes out of beta? Thanks, these look like great components.
